# Generated by Django 2.0.1 on 2018-02-02 22:06

from django.db import migrations, models
import uuid
import veiledfiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeiledFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_filename', models.CharField(editable=False, max_length=120)),
                ('file', veiledfiles.models.VeiledFileField(upload_to=uuid.uuid4)),
                ('sha1_digest', models.BinaryField(unique=True)),
            ],
        ),
    ]
