# Generated by Django 2.0.1 on 2018-01-20 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=300)),
                ('initial_filename', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=300)),
                ('full_name', models.CharField(max_length=120)),
                ('short_name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=31)),
                ('datasheets', models.ManyToManyField(to='datasheets.Datasheet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datasheet',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasheets.Manufacturer'),
        ),
    ]
