# Generated by Django 2.0.1 on 2018-01-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetspackage',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
